### ISSUE TITLE
Handle interleaved wire order

### ISSUE THREAD

**Issue by fretchen** [qiskit-community/qiskit-cold-atom#34]
### Informations

- **Qiskit Cold atoms version**: pre release
- **Python version**: 3.9
- **Operating system**: macOS

### What is the current behavior?

If `qiskit-cold-atoms` sends a circuit to the back-end it sends it with the `sequential` wire-order. However, a number of back-ends (including ours) only accept an `interleaved` wire-order and would need to write a converter.

### Steps to reproduce the problem

```
job_payload = {
        "experiment_0": {
            "instructions": [
                ["load", [7], []],
                ["load", [2], []],
                ["measure", [2], []],
                ["measure", [6], []],
                ["measure", [7], []],
            ],
            "num_wires": 8,
            "shots": 4,
            "wire_order": "sequential",
        },
    }

url= 'https://qsimsim.synqs.org/fermions/post_job/'

job_response = requests.post(url, data={'json':json.dumps(job_payload),'username': username,'password':password})
```

### What is the expected behavior?

Qiskit should send the json file with the appropiate ordering.

```
job_payload = {
        "experiment_0": {
            "instructions": [
                ["load", [7], []],
                ["load", [2], []],
                ["measure", [2], []],
                ["measure", [6], []],
                ["measure", [7], []],
            ],
            "num_wires": 8,
            "shots": 4,
            "wire_order": "interleaved",
        },
    }

url= 'https://qsimsim.synqs.org/fermions/post_job/'

job_response = requests.post(url, data={'json':json.dumps(job_payload),'username': username,'password':password})
```

### Suggested solutions

Write a converter, which is based on the configuration of the back-end.

**Comment by LaurinFischer** [comment]
I see two potential approaches to get such a converter:

1. Write a transpiler pass, which gets the qiskit circuit (which should be sequential) and the preference from the backend, and spits out a new circuit which abides by the backend convention. 
2. If we wanna keep things simpler, we could just move this into the `circuit_to_cold_atom` function of the `CircuitTools` and just do the transformation when the actual JSON is constructed that is being sent to the backend. That is, we don't actually tinker with the circuits but just put the JSONs into the right format. 

What do you think, @eggerdj ?

**Comment by eggerdj** [comment]
See #38
