### ISSUE TITLE
Docs deploy

### ISSUE THREAD

**Issue by eggerdj** [qiskit-community/qiskit-cold-atom#72]
Setup Github action to deploy the docs.

**Comment by fretchen** [comment]
Hi @Eric-Arellano . Would you have a guess why the actions do not deploy automatically ? Or anyone who knows that the way qiskit docs are normally deployed ?

**Comment by fretchen** [comment]
Fixed with #81 by @ElePT

**Comment by Eric-Arellano** [comment]
Pardon that I missed your comment, @eggerdj! I was OOO and looks like I missed it. My bad.

Thanks Elena for fixing!
