### ISSUE TITLE
qiskit-cold-atom not compatible with qiskit-nature 0.7.1

### ISSUE THREAD

**Issue by fretchen** [qiskit-community/qiskit-cold-atom#87]
### Informations

- **Qiskit Cold atoms version**:

current branch

- **Python version**:

3.10

- **Operating system**:

all

### What is the current behavior?

Trying to run tests and install qiskit-cold-atom requires to fix `qiskit-nature` to <= 0.6.2. Otherwise it raises several errors in linting and testing. The main problem seems to be:

 No name 'operators' in module 'qiskit_nature'

### Steps to reproduce the problem

All problems are produced in [this test run](https://github.com/qiskit-community/qiskit-cold-atom/actions/runs/7157540648/job/19488532688?pr=86).

### What is the expected behavior?

We should be able to cleanly work with qiskit-nature in its most current version.

**Comment by fretchen** [comment]
I tried to get started on this one in [this branch](https://github.com/Alqor-UG/qiskit-cold-atom/tree/87-qiskit-nature). However, we have to jump from the syntax of 0.4 to the syntax of 0.7 and this seems to be a fairly major shift. I think that I might have found most of the operators, but some problems and questions remain:

- It would seem that `SparseLabelOp` is the new name of `SecondQuantizedOp` ? Not sure what has to be changed to make it work.
- The `register_length` seems to not exist anymore and had to be updated to `num_spin_orbitals` or `num_spins`.
- For the moment the tests still fail with `'Gate rlx has no defined generator'`. No idea why.
- I think that we should also enable dependabot updates to avoid another massive version jump like this one in the future.

I was not sure if I should open a PR draft or just get your feedback here. Whatever you guys prefer. Ideas how to solve the issue @eggerdj or @LaurinFischer ?

**Comment by eggerdj** [comment]
Hi Fred, I think a PR would be good. Like that we can see where the tests fail and comment.

**Comment by LaurinFischer** [comment]
Hi @fretchen, 
I've opened a [new branch on my fork](https://github.com/LaurinFischer/qiskit-cold-atom/tree/qiskit-nature-0.7_migration) where I'm working on this (didn't have permission to push directly onto your PR). 
Things are working fine now, but I still have to update the tutorials and some tests. 
I'll ping you when everything is working, then I suggest you merge this into your open PR and perhaps ask Daniel to review it. 

In the latest qiskit nature, the syntax to initialize `SpinOp` and `FermionicOp` changed significantly, which required some refactoring. This means that older versions of qiskit nature will no longer be compatible.
